#@TYPE: Machine
#@NAME: CubieBoard4
#@DESCRIPTION: Machine configuration for the CubieBoard4 (CC-A80), based on Allwinner A80 (sun9i)

require conf/machine/include/sun9i.inc
require conf/machine/include/hardware/ap6330.inc

KERNEL_DEVICETREE = "allwinner/sun9i-a80-cubieboard4.dtb"
UBOOT_MACHINE = "Cubieboard4_defconfig"
